export * from "./header/Header";
export * from "./footer/Footer";
export * from "./plans/Plans";
export * from "./plan-cards";
export * from "./price/Price";
export * from "./sale/Sale";
export * from "./attention/Attention";
export * from "./privacy-policy/PrivacyPolicy";
export * from "./controls";
